spring:
  application: 
    name : get-customer-id-service
    
  jpa:
     hibernate.ddl-auto : update
     show-sql : true
  datasource :
     url : jdbc:mysql://localhost:3306/cdeproject
     username: root
     password: root

server: 
  port: 8000

