spring : 
  application :
    name: customer-config-server
  cloud : 
    config : 
      server : 
        git : 
          uri : https://github.com/MalavikaUnni/config-server-test    
server : 
  port : 8888

