spring:
  application:
    name: netflix-zuul-api-gateway-server
  jpa:
     hibernate.ddl-auto : update
     show-sql : true
  datasource :
     url : jdbc:mysql://localhost:3306/cognizant
     username: root
     password: root 
  cloud : 
    config : 
      uri : http://localhost:8888
server:
  port: 8765
  

ribbon:
  ReadTimeout : 60000
  
zuul :
  sensitiveHeaders : Cookie,Set-Cookie
  routes:
    users:
      path: /cts/superstore/**
      serviceId: get-customer-id-service